=== noahm/DDRCardDraw/songs.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Game Data",
  "description": "Describes the shape of data that any individual json file under `src/songs` will conform to",
  "additionalProperties": false,
  "required": ["songs", "meta", "defaults", "i18n"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "meta": {
      "type": "object",
      "description": "Describes unique configuration options for this game",
      "required": ["lastUpdated", "styles", "difficulties", "flags"],
      "additionalProperties": false,
      "properties": {
        "menuParent": {
          "type": "string",
          "description": "If supplied, the parent folder name in the game select menu"
        },
        "lastUpdated": {
          "type": "integer",
          "description": "Unix timestamp of last update to this data file"
        },
        "styles": {
          "$ref": "#/definitions/uniqueStringArr",
          "description": "List of all play styles available"
        },
        "difficulties": {
          "type": "array",
          "description": "List of all difficulty classes available",
          "items": {
            "type": "object",
            "properties": {
              "key": {
                "type": "string",
                "description": "A unique string key to identify this difficulty class"
              },
              "color": {
                "type": "string",
                "description": "A css color to use to visually define this difficulty class"
              }
            },
            "required": ["key", "color"],
            "additionalProperties": false
          },
          "additionalItems": false
        },
        "flags": {
          "$ref": "#/definitions/uniqueStringArr",
          "description": "List of all special flags one might filter songs by"
        },
        "folders": {
          "$ref": "#/definitions/uniqueStringArr",
          "description": "List of all possible folders, in order"
        },
        "usesDrawGroups": {
          "type": "boolean"
        },
        "granularTierResolution": {
          "type": "integer",
          "description": "Number of steps from one level to the next when using the `sanbaiTier` granular levels"
        },
        "cardVariant": {
          "type": "string",
          "description": "Specifies a unique card type which can show info tailored to a specific game"
        }
      }
    },
    "defaults": {
      "type": "object",
      "description": "Defines the default configuration for this game",
      "required": [
        "style",
        "difficulties",
        "lowerLvlBound",
        "upperLvlBound",
        "flags"
      ],
      "additionalProperties": false,
      "properties": {
        "style": { "type": "string" },
        "difficulties": { "$ref": "#/definitions/uniqueStringArr" },
        "flags": { "$ref": "#/definitions/uniqueStringArr" },
        "folders": { "$ref": "#/definitions/uniqueStringArr" },
        "lowerLvlBound": { "type": "number" },
        "upperLvlBound": { "type": "number" }
      }
    },
    "i18n": {
      "type": "object",
      "description": "Set of localized values for display of any styles, difficulties, or flags",
      "required": ["en"],
      "additionalProperties": {
        "$ref": "#/definitions/i18nDictRoot"
      }
    },
    "songs": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "Song",
        "properties": {
          "flags": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "uniqueItems": true,
            "description": "Holds info about a song that may make it worth filtering out"
          },
          "name": {
            "type": "string"
          },
          "artist": {
            "type": "string"
          },
          "genre": {
            "type": "string"
          },
          "artist_translation": {
            "type": "string"
          },
          "bpm": {
            "type": "string"
          },
          "name_translation": {
            "type": "string"
          },
          "search_hint": {
            "type": "string",
            "description": "Extra text to make this easier to find by text entry"
          },
          "date_added": {
            "type": "string"
          },
          "charts": {
            "type": "array",
            "items": { "$ref": "#/definitions/chart" },
            "additionalItems": false
          },
          "jacket": {
            "type": "string"
          },
          "folder": {
            "type": "string"
          },
          "saHash": {
            "type": "string",
            "description": "a unique identifier for a song"
          },
          "saIndex": {
            "type": "string"
          },
          "remyLink": {
            "type": "string"
          },
          "extras": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "uniqueItems": true,
            "description": "Holds cosmetic only info about a song"
          }
        },
        "required": ["name", "artist", "bpm", "jacket", "charts"],
        "additionalProperties": false
      },
      "additionalItems": false
    }
  },
  "definitions": {
    "chart": {
      "type": "object",
      "title": "Chart",
      "additionalProperties": false,
      "properties": {
        "flags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "description": "Holds info about a chart that may make it worth filtering out"
        },
        "style": { "type": "string", "description": "e.g. single/double" },
        "diffClass": {
          "type": "string",
          "description": "e.g. expert/challenge"
        },
        "lvl": {
          "type": "number",
          "description": "in-game numeric rating"
        },
        "sanbaiTier": {
          "type": "number",
          "description": "a more granular rating sourced from 3icecream, calculated based on community performance"
        },
        "drawGroup": {
          "type": "number",
          "description": "tournament-specific grouping of charts (e.g. tier)"
        },
        "maxScore": {
          "type": "number"
        },
        "jacket": {
          "type": "string"
        },
        "author": {
          "type": "string"
        },
        "editId": {
          "type": "string",
          "description": "share code for a StepManiaX edit chart (the slug in an edits.stepmaniax.com link)"
        },
        "bpm": {
          "type": "string",
          "description": "per-chart BPM range, if one applies"
        },
        "extras": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "description": "Holds cosmetic only info about a chart"
        }
      },
      "required": ["lvl", "diffClass", "style"]
    },
    "uniqueStringArr": {
      "type": "array",
      "description": "An array of strings without any duplicate values",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "i18nDictRoot": {
      "type": "object",
      "title": "I18nDict",
      "description": "Dictionary of localized strings",
      "required": ["name", "$abbr"],
      "additionalProperties": {
        "oneOf": [
          { "type": "string" },
          { "$ref": "#/definitions/i18nDictBranch" }
        ]
      }
    },
    "i18nDictBranch": {
      "type": "object",
      "additionalProperties": {
        "oneOf": [
          { "type": "string" },
          { "$ref": "#/definitions/i18nDictBranch" }
        ]
      }
    }
  }
}

=== noahm/DDRCardDraw/src/songs/bite7.json
{
  "$schema": "../../songs.schema.json",
  "meta": {
    "menuParent": "events",
    "styles": ["single", "double"],
    "difficulties": [
      { "key": "beginner", "color": "#6eccc4" },
      { "key": "basic", "color": "#e0de5c" },
      { "key": "difficult", "color": "#e8715f" },
      { "key": "expert", "color": "#72cc6e" },
      { "key": "challenge", "color": "#cc71e8" }
    ],
    "folders": [
      "DanceDanceRevolution A3",
      "DanceDanceRevolution A20 PLUS",
      "DanceDanceRevolution A20",
      "DanceDanceRevolution A",
      "DanceDanceRevolution (2014)",
      "DanceDanceRevolution (2013)",
      "DanceDanceRevolution X3 vs 2nd MIX",
      "DanceDanceRevolution X2",
      "DanceDanceRevolution X",
      "DanceDanceRevolution SuperNOVA2",
      "DanceDanceRevolution SuperNOVA",
      "DanceDanceRevolution EXTREME",
      "DDRMAX2 -DanceDanceRevolution 7thMIX-",
      "DDRMAX -DanceDanceRevolution 6thMIX-",
      "DanceDanceRevolution 5th Mix",
      "DanceDanceRevolution 4th Mix",
      "DanceDanceRevolution 3rd Mix",
      "DanceDanceRevolution 2nd Mix",
      "DanceDanceRevolution 1st Mix"
    ],
    "flags": ["shock"],
    "granularTierResolution": 20,
    "lastUpdated": 1722200089219
  },
  "defaults": {
    "style": "single",
    "difficulties": ["difficult", "expert", "challenge"],
    "flags": ["shock"],
    "lowerLvlBound": 11,
    "upperLvlBound": 19
  },
  "i18n": {
    "en": {
      "name": "BITE 7 DDR A3 Curated Charts",
      "single": "Single",
      "double": "Double",
      "beginner": "Beginner",
      "basic": "Basic",
      "difficult": "Difficult",
      "expert": "Expert",
      "challenge": "Challenge",
      "shock": "Shock arrow charts",
      "$abbr": {
        "beginner": "Beg",
        "basic": "Bas",
        "difficult": "Dif",
        "expert": "Exp",
        "challenge": "Cha"
      }
    },
    "ja": {
      "name": "BITE 7 DDR A3 Curated Charts",
      "$abbr": {
        "beginner": "Beg",
        "basic": "Bas",
        "difficult": "Dif",
        "expert": "Exp",
        "challenge": "Cha"
      }
    }
  },
  "songs": [
    {
      "name": "Beluga",
      "name_translation": "",
      "artist": "BEMANI Sound Team \"S-C-U\"",
      "artist_translation": "",
      "bpm": "132",
      "folder": "DanceDanceRevolution A3",
      "charts": [
        {
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11.4
        }
      ],
      "remyLink": "http://remywiki.com/Beluga",
      "jacket": "ddr_a3/Beluga.jpg",
      "saHash": "DqoQD9iDodq9Iq108l119OQ1olOPi6D1",
      "saIndex": "1073"
    },
    {
      "name": "Get On Da Floor",
      "name_translation": "",
      "artist": "DJ Shimamura",
      "artist_translation": "",
      "bpm": "140",
      "folder": "DanceDanceRevolution A20",
      "charts": [
        {
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11.45
        }
      ],
      "remyLink": "http://remywiki.com/Get%20On%20Da%20Floor",
      "jacket": "ddr_a20/Get On Da Floor.png",
      "genre": "",
      "saHash": "Pq0Qq0OQqlPDQOld8bddlIDPD89o8bO8",
      "saIndex": "840"
    },
    {
      "name": "Love♡Shine わんだふるmix",
      "name_translation": "Love Shine wonderful mix",
      "artist": "ARM(IOSYS) feat.一ノ瀬月琉",
      "artist_translation": "ARM (IOSYS) feat. Ruru Ichinose (monotone)",
      "bpm": "177",
      "folder": "DanceDanceRevolution A",
      "charts": [
        {
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11.35
        }
      ],
      "remyLink": "http://remywiki.com/Love%E2%99%A1Shine%20%E3%82%8F%E3%82%93%E3%81%A0%E3%81%B5%E3%82%8Bmix",
      "jacket": "ddr_a/Love Shine wonderful mix.png",
      "genre": "",
      "saHash": "qi9qP1dPd6PPDlldbb8OIlD08Pbd9006",
      "saIndex": "811"
    },
    {
      "name": "Our Soul",
      "name_translation": "",
      "artist": "CaZ",
      "artist_translation": "",
      "bpm": "150",
      "folder": "DanceDanceRevolution A20",
      "charts": [
        {
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11.15
        }
      ],
      "remyLink": "http://remywiki.com/Our%20Soul",
      "jacket": "ddr_a20/Our Soul.png",
      "genre": "",
      "saHash": "QI06q9lPIoo80DlI18Ooi6dbPl89bqi0",
      "saIndex": "860"
    },
    {
      "name": "Party Rock Anthem",
      "name_translation": "",
      "artist": "LMFAO",
      "artist_translation": "",
      "bpm": "130",
      "folder": "DanceDanceRevolution A20",
      "charts": [
        {
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11.35
        }
      ],
      "remyLink": "http://remywiki.com/Party%20Rock%20Anthem",
      "jacket": "ddr_a20/Party Rock Anthem.png",
      "genre": "",
      "saHash": "09oIbO1bi8O8Q1o01q610ID0qPOqoQQP",
      "saIndex": "875"
    },
    {
      "name": "Show me your moves",
      "name_translation": "",
      "artist": "BEMANI Sound Team \"TAG\" feat. 柊木りお",
      "artist_translation": "BEMANI Sound Team \"TAG\" feat. Rio Hiiragi",
      "bpm": "155",
      "folder": "DanceDanceRevolution A",
      "charts": [
        {
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11.15
        }
      ],
      "remyLink": "http://remywiki.com/Show%20me%20your%20moves",
      "jacket": "ddr_a/Show me your moves.png",
      "genre": "",
      "saHash": "6oolbQ0QiO90Dd0DQbb1D86d8q88id86",
      "saIndex": "812"
    },
    {
      "name": "Special One",
      "name_translation": "",
      "artist": "kors k feat. Suzuyo Miyamoto",
      "artist_translation": "",
      "bpm": "128",
      "folder": "DanceDanceRevolution A",
      "charts": [
        {
          "maxScore": 789,
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11.35
        }
      ],
      "remyLink": "http://remywiki.com/Special%20One",
      "jacket": "ddr_a/Special One.png",
      "genre": "J-HOUSE",
      "saHash": "D9odQ60DDolq9QI9DDl98DIobdPPIil9",
      "saIndex": "721"
    },
    {
      "name": "Stay 4 Ever",
      "name_translation": "",
      "artist": "CHEAP CREAM",
      "artist_translation": "",
      "bpm": "140",
      "folder": "DanceDanceRevolution A20",
      "charts": [
        {
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11.15
        }
      ],
      "remyLink": "http://remywiki.com/Stay%204%20Ever",
      "jacket": "ddr_a20/Stay 4 Ever.png",
      "saHash": "olDoq69qD008Q9bb8d9OOlPO160Qd0dq",
      "saIndex": "903"
    },
    {
      "name": "この青空の下で",
      "name_translation": "Kono aoi sora no shita de",
      "artist": "TAG meets \"eimy\"",
      "artist_translation": "",
      "bpm": "165",
      "folder": "DanceDanceRevolution A",
      "charts": [
        {
          "maxScore": 1233,
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11
        }
      ],
      "remyLink": "http://remywiki.com/%E3%81%93%E3%81%AE%E9%9D%92%E7%A9%BA%E3%81%AE%E4%B8%8B%E3%81%A7",
      "jacket": "ddr_a/Kono aozora no shita de.png",
      "genre": "",
      "saHash": "qbbPQoqqqiPd98d61P0qDd0iDId6OqoQ",
      "saIndex": "692"
    },
    {
      "name": "朧",
      "name_translation": "Oboro",
      "artist": "HHH×MM×ST",
      "artist_translation": "",
      "bpm": "149",
      "folder": "DanceDanceRevolution A",
      "charts": [
        {
          "maxScore": 1269,
          "lvl": 11,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 11.15
        }
      ],
      "remyLink": "http://remywiki.com/%E6%9C%A7",
      "jacket": "ddr_a/Oboro.png",
      "genre": "FASCINATION",
      "saHash": "I96dOqqqQIi9oiqbqDPbQ8I8PQbqOb1o",
      "saIndex": "691"
    },
    {
      "name": "Alone",
      "name_translation": "",
      "artist": "Marshmellow",
      "artist_translation": "",
      "bpm": "142",
      "folder": "DanceDanceRevolution A20",
      "charts": [
        {
          "lvl": 12,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 12.05
        }
      ],
      "remyLink": "http://remywiki.com/Alone",
      "jacket": "ddr_a20/Alone.png",
      "genre": "",
      "saHash": "bdbQoi98Dlb18DiPDPdD801DoOD8619O",
      "saIndex": "870"
    },
    {
      "name": "Bad Apple!! feat. nomico",
      "name_translation": "",
      "artist": "Masayoshi Minoshima",
      "artist_translation": "",
      "bpm": "138",
      "folder": "DanceDanceRevolution A",
      "charts": [
        {
          "maxScore": 1317,
          "lvl": 12,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 12.3
        }
      ],
      "remyLink": "http://remywiki.com/Bad%20Apple%21%21%20feat.%20nomico",
      "jacket": "ddr_a/Bad Apple!! feat. nomico.png",
      "genre": "",
      "saHash": "8Q8dP1odl1D9lIbiIO86OPPIoq6qPP1l",
      "saIndex": "679"
    },
    {
      "name": "bass 2 bass",
      "name_translation": "",
      "artist": "Ryu☆",
      "artist_translation": "",
      "bpm": "140",
      "folder": "DanceDanceRevolution A",
      "charts": [
        {
          "maxScore": 1122,
          "lvl": 12,
          "style": "single",
          "diffClass": "expert",
          "sanbaiTier": 12.35
        }
      ],
      "remyLink": "http://remywiki.com/Bass%202%20bass",
      "jacket": "ddr_a/bass 2 bass.png",
      "genre": "BUBBLEGUM DANCE",
      "saHash": "18id0bi1Q6lbl0091iP0QoOIq9DDPo9I",
      "saIndex": "695"
    },
    {
      "name": "CHOCOLATE PHILOSOPHY",
      "name_translation": "",
      "artist": "常盤ゆう",
      "artist_translation": "YUU TOKIWA",
      "bpm": "220",
      "folder": "DanceDanceRevolution A",
      "charts": [
        {
